from importlib import import_module
import sys

from .accounts import (
    AccountRegistry,
    AccountRotationOrchestrator,
    BrowserProfileSwitcher,
    CredentialVault,
    DPAPICipher,
    ExternalCredentialInjector,
    MultiAccountLoadBalancer,
    RequestsVaultAPIBackend,
    SessionStateTracker,
    SubprocessBrowserLauncher,
    VaultAPIError,
)
from .agents import (
    AgentHandoffProtocol,
    AgentMessageBus,
    DesktopAutomationAgent,
    HierarchicalTaskDecomposer,
    IPCModule,
    OrchestratorAgentCore,
    ParallelWorkerPool,
    SandboxIsolationManager,
    SharedStateManager,
    SpecialistAgentRouter,
    TaskQueueManager,
)

def create_agent() -> DesktopAutomationAgent:
    """Factory function to create a pre-configured DesktopAutomationAgent with all core specialists."""
    agent = DesktopAutomationAgent()

    # 1. Initialize Core Infrastructure
    window_manager = DesktopWindowManager()
    screenshot_backend = PyAutoGUIScreenshotBackend()
    template_matcher = TemplateImageMatcher(backend=OpenCVImageMatcherBackend())
    accessibility_reader = AccessibilityTreeReader()
    ocr_backend = TesseractOCRBackend()
    ocr_extractor = OCRExtractor(backend=ocr_backend)

    # 2. Initialize Safe Input Simulator
    import pyautogui
    width, height = pyautogui.size()
    input_backend = PyAutoGUIBackend.create()
    screen_inspector = StaticScreenInspector(bounds=ScreenBounds(width=width, height=height))
    input_runner = SafeInputSimulator(
        backend=input_backend,
        window_manager=Win32WindowManager(),
        screen_inspector=screen_inspector
    )

    # 3. Instantiate Specialists

    # Application Launcher
    app_registry = ApplicationRegistry(storage_path="data/app_registry.json")
    app_launcher_backend = SubprocessApplicationLauncherBackend()
    app_launcher = ApplicationLauncher(
        registry=app_registry,
        backend=app_launcher_backend,
        window_manager=window_manager,
        accessibility_reader=accessibility_reader,
        ocr_extractor=ocr_extractor,
        template_matcher=template_matcher,
        screenshot_backend=screenshot_backend
    )
    agent.register_specialist("application_launcher", app_launcher, ["launch", "open", "start app"])

    # Navigation Step Sequencer
    state_verifier = ScreenStateVerifier(
        ocr_extractor=ocr_extractor,
        template_matcher=template_matcher,
        window_manager=window_manager,
        accessibility_reader=accessibility_reader,
        screenshot_backend=screenshot_backend
    )
    nav_sequencer = NavigationStepSequencer(
        input_runner=input_runner,
        verifier=state_verifier,
        launcher=app_launcher
    )
    agent.register_specialist("navigation_step_sequencer", nav_sequencer, ["navigate", "click", "scroll", "verify", "wait"])

    # Form Automation
    form_automation = FormAutomationModule(
        input_runner=input_runner,
        accessibility_reader=accessibility_reader,
        ocr_extractor=ocr_extractor,
        window_manager=window_manager
    )
    agent.register_specialist("form_automation", form_automation, ["fill", "enter", "submit", "form", "write"])

    # AI Interface Navigator
    clipboard_manager = ClipboardManager(backend=Win32ClipboardBackend())
    prompt_injector = TargetApplicationPromptInjector(
        input_runner=input_runner,
        window_manager=window_manager,
        clipboard_manager=clipboard_manager,
        accessibility_reader=accessibility_reader,
        ocr_extractor=ocr_extractor
    )
    ai_navigator = AIInterfaceNavigator(
        prompt_injector=prompt_injector,
        input_runner=input_runner,
        screenshot_backend=screenshot_backend,
        accessibility_reader=accessibility_reader,
        ocr_extractor=ocr_extractor,
        template_matcher=template_matcher,
        window_manager=window_manager
    )
    agent.register_specialist("ai_interface_navigator", ai_navigator, ["chat", "prompt", "ai", "llm", "ask"])

    return agent

from .ai import (
    AIInterfaceNavigator,
    PromptPerformanceTracker,
    PromptPipelineRunner,
    PromptTemplateManager,
    ResponseExtractorParser,
)
from .automation import (
    AutomationPluginLoader,
    ApplicationLauncher,
    ApplicationRegistry,
    CICDPipelineIntegrationModule,
    ConditionalBranchEvaluator,
    COMAutomationConnector,
    DataExportPipeline,
    ExternalWorkflowTriggerReceiver,
    FileBasedDataExchange,
    FormAutomationModule,
    GraphBasedWorkflowPlanner,
    LangGraphNodeDefinition,
    LangGraphStateConnector,
    MenuDialogNavigator,
    MCPToolAdapter,
    MCPToolCallRequest,
    MCPToolDefinition,
    MultiApplicationWorkflowCoordinator,
    NavigationStepSequencer,
    PluginActionRouter,
    RESTAPIActionExecutor,
    StructuredDataExtractor,
    SubprocessApplicationLauncherBackend,
    TargetApplicationPromptInjector,
    TriggerAuthenticationConfiguration,
    WebDesktopHybridAutomation,
    Win32PlatformTextInputBackend,
    WorkflowReportGenerator,
    WorkflowScheduler,
    WorkflowTemplateLibrary,
    WorkflowVersionController,
)
from .desktop import (
    AccessibilityTreeReader,
    AdaptiveTimingCalibrator,
    AnimationTransitionWaitModule,
    ClipboardManager,
    ClipboardDataBridge,
    DesktopPerceptionEngine,
    DesktopWindowManager,
    EventDrivenTriggerListener,
    InterStepPacingController,
    MultiMonitorDisplayHandler,
    DynamicRegionOfInterestCalculator,
    MultiStrategyElementLocator,
    OCRExtractor,
    OpenCVImageMatcherBackend,
    PILDifferenceBackend,
    PILVirtualDesktopCaptureBackend,
    PyAutoGUIBackend,
    PyAutoGUIScreenCaptureBackend,
    PyAutoGUIScreenshotBackend,
    ResolutionAdaptiveCoordinateManager,
    ScreenBrightnessThemeHeuristic,
    SafeInputSimulator,
    SmartWaitEngine,
    ScreenChangeDetectionMonitor,
    ScreenStateVerifier,
    StaticScreenInspector,
    StartupTimingBenchmark,
    TemplateImageMatcher,
    ThemeAdaptationModule,
    TesseractOCRBackend,
    UIStateFingerprinter,
    Win32ClipboardBackend,
    Win32MonitorBackend,
    Win32ThemeBackend,
    Win32WindowBackend,
    Win32WindowManager,
)
from .knowledge import (
    ActionHistoryAnalyzer,
    EpisodicMemoryLogger,
    FeedbackLoopCollector,
    SelfCritiqueImprovementLoop,
    WorkflowSkillStore,
)
from .observability import (
    AnomalyDetector,
    ComplianceAuditReportGenerator,
    DatabaseLoggingBackend,
    ExecutionTraceRecorder,
    NotificationDispatcher,
    PerformanceMetricsCollector,
    RealTimeDashboardDataProvider,
    ResourceUsageTracker,
    ScreenshotOnFailureRecorder,
    SLAMonitor,
    SQLiteConnectionPool,
    WatchdogTimer,
    WorkflowAuditLogger,
)
from .resilience import (
    ApprovalGateModule,
    AntiLoopDetector,
    ActionAllowlistEnforcer,
    CheckpointManager,
    ConfidenceBasedAutoRouting,
    DeadLetterQueueHandler,
    EscalationManager,
    ErrorClassifier,
    ExponentialBackoffRetryEngine,
    FailSafeController,
    HumanReviewInterface,
    IdempotencyGuard,
    KeyboardHotkeyBackend,
    PrePostConditionValidator,
    PyAutoGUIPointerBackend,
    RateLimiter,
    RetryExhaustedError,
    SelfHealingRecoveryModule,
    SensitiveDataProtector,
)
from .models import (
    ActionLogEntry,
    ActiveWorkflowStatus,
    AntiLoopDetectionResult,
    AntiLoopEventRecord,
    AntiLoopStepExecution,
    AntiLoopTriggerType,
    AllowlistCheckRequest,
    AllowlistCheckResult,
    AllowlistRuleSet,
    AllowlistScope,
    AccessibilityElement,
    AccessibilityElementState,
    AccessibilityQueryResult,
    AccessibilityTree,
    AdaptiveTimingBaselineRecord,
    AdaptiveTimingCalibrationResult,
    AdaptiveTimingSessionProfile,
    AnimationCompletionSignal,
    AnimationWaitLogEntry,
    AnimationWaitRequest,
    AnimationWaitResult,
    AIInterfaceConfiguration,
    AIInterfaceElementMatch,
    AIInterfaceElementSelector,
    AIInterfaceNavigationResult,
    AIInterfaceObservation,
    AIInterfaceStatus,
    AIInterfaceSubmitMode,
    ApplicationLaunchAttempt,
    ApplicationLaunchMode,
    ApplicationLaunchRequest,
    ApplicationLaunchResult,
    ApplicationLaunchStatus,
    ApplicationRegistrySnapshot,
    ApplicationStartupSignature,
    AutomationPluginDeclaration,
    AutomationPluginExecutionResult,
    AutomationPluginLoaderResult,
    AutomationPluginRecord,
    BranchComparisonOperator,
    BranchConditionSpecification,
    BranchConditionType,
    BranchEvaluationContext,
    BranchEvaluationRecord,
    BranchEvaluationResult,
    BranchOption,
    BranchValueSource,
    CICDReportMode,
    CICDRunResult,
    CICDStepOutcome,
    CICDTriggerPayload,
    CICDWorkflowSpecification,
    AnomalyCategory,
    AnomalyDetectionResult,
    AnomalyRecord,
    PipelinePauseDecision,
    PipelineReviewRequest,
    PipelineReviewResult,
    PipelineResponseAction,
    PipelineStatus,
    RetryAttemptLog,
    RetryConfiguration,
    RetryDisposition,
    RetryExceptionRule,
    RetryFailureResult,
    SandboxAccessAttempt,
    SandboxAccessType,
    SandboxIsolationMode,
    SandboxIsolationPolicy,
    SandboxIsolationResult,
    SandboxViolationRecord,
    SandboxWorkerLaunchSpec,
    RESTAPICallLog,
    RESTAPIExecutorResult,
    RESTAPIMethod,
    RESTAPIRequest,
    RESTAPIResponse,
    RateLimiterResult,
    RateLimiterSnapshot,
    RateLimitExecutionRecord,
    RateLimitRequest,
    RateLimitRule,
    RateLimitScope,
    RateLimitWindow,
    RateUsageMetric,
    RecoveryStrategy,
    TaskPriority,
    TaskQueueAlert,
    TaskQueueDepthMetric,
    TaskQueueOperationResult,
    TaskQueueSnapshot,
    ResponseExtractionAttempt,
    ResponseExtractionConfiguration,
    ResponseExtractionResult,
    FailSafeActivationRecord,
    FailSafeActivationResult,
    FailSafeResourceReleaseResult,
    FailSafeTriggerType,
    ResponseProcessingMode,
    ResponseValidationMode,
    ResponseValidationResult,
    ResourceUsageAggregate,
    ResourceUsageRunRecord,
    ResourceUsageTrackerResult,
    ResourceUsageTrendReport,
    ResourceUsageTrendSnapshot,
    ResourceUsageSnapshot,
    SLAAlertRecord,
    SLAComplianceSnapshot,
    SLADailyPerformanceReport,
    SLAMonitorResult,
    SLARecordedStepDuration,
    SLARunRecord,
    SLASlowestStepContribution,
    SLAWorkflowConfiguration,
    TaskDecompositionLevel,
    TaskDecompositionNode,
    TaskDecompositionResult,
    TaskDecompositionTree,
    ImprovementProposalRecord,
    ImprovementProposalStatus,
    ImprovementTargetType,
    IPCChannelType,
    IPCConnectionRecord,
    IPCMessage,
    IPCOperationResult,
    IPCSnapshot,
    AccountRecord,
    AccountExecutionMode,
    AccountLoadMetric,
    AccountRegistryResult,
    AccountRegistrySnapshot,
    AccountRotationResult,
    AccountUsageEvent,
    ApprovalDecision,
    ApprovalGateAction,
    ApprovalGateResult,
    ApprovalRequest,
    ApprovalResponse,
    ApprovalRiskLevel,
    ApprovalTimeoutPolicy,
    ConfidenceRoutingDecision,
    ConfidenceRoutingDisposition,
    ConfidenceRoutingResult,
    ConfidenceRoutingSnapshot,
    ConfidenceThresholdRule,
    EscalationManagerResult,
    EscalationRecord,
    EscalationRequest,
    EscalationResolution,
    EscalationResponse,
    EscalationSnapshot,
    EscalationTriggerType,
    ExecutionTraceEvent,
    ExecutionTraceEventType,
    ExecutionTraceRecord,
    ExecutionTraceResult,
    HumanReviewDecisionRecord,
    HumanReviewDecisionType,
    HumanReviewInterfaceResult,
    HumanReviewInterfaceSnapshot,
    HumanReviewPendingItem,
    AutomationTask,
    ActionFailurePoint,
    ActionHistoryAnalysisReport,
    ActionHistoryAnalysisResult,
    ActionHistorySequencePattern,
    AgentBusDeliveryResult,
    AgentBusMessage,
    AgentBusSubscription,
    AgentHandoffContext,
    AgentHandoffReason,
    AgentHandoffRecord,
    AgentHandoffResult,
    RotationExecutionEvent,
    RotationExecutionSnapshot,
    RotationTask,
    BrowserProfileRecord,
    BrowserProfileResult,
    BrowserProfileSnapshot,
    BrowserSessionRecord,
    CheckpointDecision,
    CheckpointRestoreResult,
    CheckpointResumePolicy,
    ClipboardContent,
    ClipboardContentType,
    ClipboardBridgeFormat,
    ClipboardBridgeResult,
    ClipboardEvent,
    ClipboardOperationResult,
    ClipboardPasteMode,
    ClipboardVerificationResult,
    ComplianceAccountSessionRecord,
    ComplianceActionRecord,
    ComplianceApprovalRecord,
    ComplianceAuditReport,
    ComplianceAuditReportResult,
    ComplianceEscalationRecord,
    ComplianceFailureRecord,
    ComplianceSensitiveAccessRecord,
    COMAutomationResult,
    COMAutomationSession,
    ConditionDescription,
    ConditionValidationResult,
    CoordinateAdaptationResult,
    DashboardAccountStatus,
    DashboardDataProviderResult,
    DashboardSnapshot,
    DashboardWorkerStatus,
    DatabaseBufferedOperation,
    DatabaseCheckpointRecord,
    DatabaseErrorRecord,
    DatabaseExtractedDataRecord,
    DatabaseLoggingResult,
    DatabaseLoggingSnapshot,
    DatabaseLogOperationType,
    DatabaseMetricRecord,
    DatabaseStepRecord,
    DatabaseWorkflowEventRecord,
    DatabaseWorkflowRecord,
    DynamicRegionOfInterest,
    DynamicRegionResult,
    DisplayConfigurationChangeResult,
    DisplayConfigurationSnapshot,
    CredentialAccessEvent,
    CredentialKind,
    CredentialRecord,
    CredentialVaultResult,
    CredentialVaultSnapshot,
    SecureCredentialValue,
    SensitiveAccessEvent,
    SensitiveProtectionResult,
    DataExportDestination,
    DataExportDestinationType,
    DataExportFileFormat,
    DataExportLogEntry,
    DataExportResult,
    DataExportValidationFailure,
    FileDataExchangeResult,
    HybridAutomationResult,
    HybridAutomationSession,
    DeadLetterItem,
    DeadLetterOperationResult,
    DeadLetterSnapshot,
    DesktopState,
    AutomationEpisode,
    EpisodicMemoryResult,
    EpisodicMemorySearchMatch,
    FeedbackEventRecord,
    FeedbackEventType,
    FeedbackLoopResult,
    FeedbackPatternSummary,
    ErrorCategory,
    ErrorClassificationRecord,
    ErrorClassificationResult,
    FailSafeActivationRecord,
    FailSafeActivationResult,
    FailSafeResourceReleaseResult,
    FailSafeTriggerType,
    FailureArchiveQuery,
    FailureArchiveRecord,
    FailureArchiveResult,
    InputAction,
    InputActionType,
    InputSimulationResult,
    InputTarget,
    DialogClassification,
    DialogHandlingRequest,
    DialogResponse,
    EventTriggerDefinition,
    EventTriggerListenerResult,
    EventTriggerListenerStatus,
    EventTriggerRecord,
    FormAutomationResult,
    FormFieldContext,
    FormFieldResult,
    FormFieldType,
    FormFieldValue,
    IdempotencyRecord,
    IdempotencyResult,
    IdempotencySnapshot,
    InteractionStateSnapshot,
    MenuDialogInteractionLog,
    MenuDialogNavigationResult,
    MenuNavigationRequest,
    WorkflowContext,
    WorkflowGraphCondition,
    WorkflowGraphConditionOperator,
    WorkflowGraphDefinition,
    WorkflowGraphEdge,
    WorkflowGraphEdgeType,
    WorkflowGraphNode,
    WorkflowGraphNodeType,
    WorkflowGraphPlanResult,
    WorkflowGraphState,
    WorkflowDefinitionVersion,
    WorkflowCheckpoint,
    WorkflowCoordinatorResult,
    WorkflowDataExchangeMode,
    WorkflowExchangeRequest,
    WorkflowStep,
    WorkflowStepResult,
    NavigationSequenceMode,
    NavigationSequenceResult,
    NavigationStep,
    NavigationStepActionType,
    NavigationStepOutcome,
    NotificationChannel,
    NotificationChannelType,
    NotificationDispatchRecord,
    NotificationDispatcherResult,
    NotificationDispatcherSnapshot,
    NotificationEventType,
    NotificationMessage,
    LocatorCandidate,
    LocatorResult,
    LocatorStrategy,
    LocatorTarget,
    LineEndingStyle,
    LoadBalancerDecisionRecord,
    LoadBalancerResult,
    LoadBalancerSnapshot,
    OCRExtractionResult,
    OCRTextBlock,
    OCRTextMatchResult,
    PacingAssignment,
    PacingContext,
    PacingDecision,
    PacingProfile,
    PluginActionRoute,
    ActionOptimizationHint,
    ActionRetryRateSummary,
    ActionStepDurationSummary,
    KnownApplicationRecord,
    OrchestratorAgentResult,
    OrchestratorExecutionSummary,
    OrchestratorSubtask,
    OrchestratorSubtaskResult,
    OrchestratorSubtaskStatus,
    OrchestratorTaskPlan,
    PerceptionArtifact,
    PerceptionResult,
    PerceptionSource,
    PerformanceMetricsResult,
    PerformanceMetricsSnapshot,
    MetricsDegradationDirection,
    MetricsDegradationRecord,
    MonitorDescriptor,
    PromptFieldContext,
    PromptInjectionMethod,
    PromptInjectionResult,
    PromptInjectionTarget,
    PromptPerformanceRecord,
    PromptPerformanceReport,
    PromptPerformanceResult,
    PromptPipelineResult,
    PromptPipelineStep,
    PromptPipelineStepLog,
    PromptReadbackMethod,
    PromptTemplatePerformanceSummary,
    WorkflowReportResult,
    WorkflowReportSummary,
    WorkflowReportTimelineItem,
    WorkflowRunReport,
    ReferenceTemplateMetadata,
    ResolutionCalibrationProfile,
    ResolutionReferenceElement,
    ResolutionVerificationReference,
    ResolutionVerificationResult,
    ScreenChangeEvent,
    ScreenChangeResult,
    ScreenCheckType,
    SelfCritiqueResult,
    SharedStateConflictPolicy,
    SharedStateField,
    SharedStateResult,
    SharedStateSnapshot,
    SharedStateWriteLog,
    PaginationAdvanceMode,
    PaginationConfiguration,
    ScreenVerificationCheck,
    ScreenVerificationCheckResult,
    ScreenVerificationResult,
    SelfHealingRecoveryRequest,
    SelfHealingRecoveryResult,
    SpecialistAgentRecord,
    SpecialistRouterResult,
    BusRecipientKind,
    SessionHealthEvent,
    SessionState,
    SessionTrackerSnapshot,
    SessionValidationResult,
    ScreenBounds,
    SmartWaitLogEntry,
    SmartWaitRequest,
    SmartWaitResult,
    StepExecutionRateStatus,
    TemplateCaptureResult,
    TemplateMatch,
    TemplateSearchRequest,
    TemplateSearchResult,
    ThemeDetectionResult,
    ThemeTemplateReferenceSet,
    TriggerType,
    UILandmark,
    UITheme,
    UIStateFingerprint,
    UnexpectedDialogPolicy,
    ValidationDisposition,
    ValidationPhase,
    WaitType,
    RoutingDecisionRecord,
    WatchdogEvent,
    WatchdogEventType,
    WatchdogStatus,
    WorkflowAuditLogEntry,
    WorkflowAuditOutcome,
    WorkflowAuditQuery,
    WorkflowAuditResult,
    WorkflowContext,
    WorkflowCheckpoint,
    WorkflowGraphCondition,
    WorkflowGraphConditionOperator,
    WorkflowGraphDefinition,
    WorkflowDefinitionVersion,
    WorkflowGraphEdge,
    WorkflowGraphEdgeType,
    WorkflowGraphNode,
    WorkflowGraphNodeType,
    WorkflowGraphPlanResult,
    WorkflowGraphState,
    WorkflowCoordinatorResult,
    WorkflowDataExchangeMode,
    WorkflowExchangeRequest,
    WorkflowSkillDocument,
    WorkflowSkillSearchMatch,
    WorkflowSkillStep,
    WorkflowSkillStoreResult,
    WorkflowSkillVersion,
    WorkflowTemplateCompositionComponent,
    WorkflowTemplateDocument,
    WorkflowTemplateLibraryResult,
    WorkflowTemplateLibrarySnapshot,
    WorkflowTemplateParameter,
    WorkflowTemplateSearchMatch,
    WorkflowTemplateVersion,
    StructuredDataExtractionConfiguration,
    StructuredDataExtractionMode,
    StructuredDataExtractionResult,
    StructuredDataFieldSchema,
    StructuredDataFieldType,
    StructuredDataPageResult,
    StructuredDataRecord,
    StructuredDataSchema,
    StepExecutionRateStatus,
    StepLatencySummary,
    StepRetryRateMetric,
    VaultCredentialAccessEvent,
    VaultCredentialCacheEntry,
    VaultCredentialResult,
    WorkflowSuccessMetric,
    WorkflowEventTrigger,
    WorkflowEventType,
    WorkflowRunRecord,
    WorkflowSchedule,
    WorkflowSchedulerEvent,
    WorkflowSchedulerResult,
    WorkflowSchedulerSnapshot,
    WorkflowVersionControlResult,
    WorkflowVersionDiff,
    WorkflowVersionSnapshot,
    WorkflowVersionTag,
    WorkflowTriggerType,
    SandboxAccessAttempt,
    SandboxAccessType,
    SandboxIsolationMode,
    SandboxIsolationPolicy,
    SandboxIsolationResult,
    SandboxViolationRecord,
    SandboxWorkerLaunchSpec,
    WorkerAssignment,
    WorkerExecutionMode,
    WorkerPoolOperationResult,
    WorkerPoolSnapshot,
    WorkerRecord,
    WorkerSessionContext,
    WorkerStatus,
    MissedExecutionPolicy,
    ThrottlingEvent,
    ThrottlingEventType,
    WorkflowStep,
    WorkflowStepResult,
    WindowContext,
    WindowOperationResult,
    WindowReference,
    WindowZone,
    WindowZoneType,
    WindowState
)

_LEGACY_MODULE_ALIASES = {
    "desktop_automation_agent.accessibility_tree_reader": ".desktop.accessibility_tree_reader",
    "desktop_automation_agent.adaptive_timing_calibrator": ".desktop.adaptive_timing_calibrator",
    "desktop_automation_agent.account_registry": ".accounts.account_registry",
    "desktop_automation_agent.account_rotation_orchestrator": ".accounts.account_rotation_orchestrator",
    "desktop_automation_agent.action_history_analyzer": ".knowledge.action_history_analyzer",
    "desktop_automation_agent.approval_gate": ".resilience.approval_gate",
    "desktop_automation_agent.anti_loop_detector": ".resilience.anti_loop_detector",
    "desktop_automation_agent.allowlist_enforcer": ".resilience.allowlist_enforcer",
    "desktop_automation_agent.agent_handoff_protocol": ".agents.agent_handoff_protocol",
    "desktop_automation_agent.agent_message_bus": ".agents.agent_message_bus",
    "desktop_automation_agent.ai_interface_navigator": ".ai.ai_interface_navigator",
    "desktop_automation_agent.anomaly_detector": ".observability.anomaly_detector",
    "desktop_automation_agent.automation_plugin_loader": ".automation.plugin_loader",
    "desktop_automation_agent.application_launcher": ".automation.application_launcher",
    "desktop_automation_agent.browser_profile_switcher": ".accounts.browser_profile_switcher",
    "desktop_automation_agent.change_detection_monitor": ".desktop.change_detection_monitor",
    "desktop_automation_agent.checkpoint_manager": ".resilience.checkpoint_manager",
    "desktop_automation_agent.clipboard": ".desktop.clipboard",
    "desktop_automation_agent.clipboard_data_bridge": ".desktop.clipboard_data_bridge",
    "desktop_automation_agent.compliance_audit_report_generator": ".observability.compliance_audit_report_generator",
    "desktop_automation_agent.com_automation_connector": ".automation.com_automation_connector",
    "desktop_automation_agent.condition_validator": ".resilience.condition_validator",
    "desktop_automation_agent.confidence_based_auto_routing": ".resilience.confidence_based_auto_routing",
    "desktop_automation_agent.credential_vault": ".accounts.credential_vault",
    "desktop_automation_agent.cicd_pipeline_integration": ".automation.cicd_pipeline_integration",
    "desktop_automation_agent.external_credential_injector": ".accounts.external_credential_injector",
    "desktop_automation_agent.data_export_pipeline": ".automation.data_export_pipeline",
    "desktop_automation_agent.file_based_data_exchange": ".automation.file_based_data_exchange",
    "desktop_automation_agent.hybrid_automation": ".automation.web_desktop_hybrid_automation",
    "desktop_automation_agent.human_review_interface": ".resilience.human_review_interface",
    "desktop_automation_agent.dead_letter_queue": ".resilience.dead_letter_queue",
    "desktop_automation_agent.external_workflow_trigger_receiver": ".automation.external_workflow_trigger_receiver",
    "desktop_automation_agent.dynamic_region_of_interest_calculator": ".desktop.dynamic_region_of_interest_calculator",
    "desktop_automation_agent.display_handler": ".desktop.display_handler",
    "desktop_automation_agent.escalation_manager": ".resilience.escalation_manager",
    "desktop_automation_agent.engine": ".desktop.engine",
    "desktop_automation_agent.episodic_memory_logger": ".knowledge.episodic_memory_logger",
    "desktop_automation_agent.feedback_loop_collector": ".knowledge.feedback_loop_collector",
    "desktop_automation_agent.error_classifier": ".resilience.error_classifier",
    "desktop_automation_agent.fail_safe_controller": ".resilience.fail_safe_controller",
    "desktop_automation_agent.form_automation": ".automation.form_automation",
    "desktop_automation_agent.idempotency_guard": ".resilience.idempotency_guard",
    "desktop_automation_agent.input_simulator": ".desktop.input_simulator",
    "desktop_automation_agent.ipc_module": ".agents.ipc_module",
    "desktop_automation_agent.hierarchical_task_decomposer": ".agents.hierarchical_task_decomposer",
    "desktop_automation_agent.locator": ".desktop.locator",
    "desktop_automation_agent.load_balancer": ".accounts.load_balancer",
    "desktop_automation_agent.database_logging_backend": ".observability.database_logging_backend",
    "desktop_automation_agent.graph_workflow_planner": ".automation.graph_workflow_planner",
    "desktop_automation_agent.workflow_version_controller": ".automation.workflow_version_controller",
    "desktop_automation_agent.workflow_template_library": ".automation.workflow_template_library",
    "desktop_automation_agent.conditional_branch_evaluator": ".automation.conditional_branch_evaluator",
    "desktop_automation_agent.menu_dialog_navigator": ".automation.menu_dialog_navigator",
    "desktop_automation_agent.mcp_tool_adapter": ".automation.mcp_tool_adapter",
    "desktop_automation_agent.langgraph_state_connector": ".automation.langgraph_state_connector",
    "desktop_automation_agent.multi_application_workflow_coordinator": ".automation.multi_application_workflow_coordinator",
    "desktop_automation_agent.navigation_step_sequencer": ".automation.navigation_step_sequencer",
    "desktop_automation_agent.notification_dispatcher": ".observability.notification_dispatcher",
    "desktop_automation_agent.ocr_extractor": ".desktop.ocr_extractor",
    "desktop_automation_agent.desktop_automation_agent": ".agents.desktop_automation_agent",
    "desktop_automation_agent.orchestrator_agent_core": ".agents.orchestrator_agent_core",
    "desktop_automation_agent.parallel_worker_pool": ".agents.parallel_worker_pool",
    "desktop_automation_agent.sandbox_isolation_manager": ".agents.sandbox_isolation_manager",
    "desktop_automation_agent.performance_metrics_collector": ".observability.performance_metrics_collector",
    "desktop_automation_agent.prompt_performance_tracker": ".ai.prompt_performance_tracker",
    "desktop_automation_agent.prompt_pipeline_runner": ".ai.prompt_pipeline_runner",
    "desktop_automation_agent.prompt_template_manager": ".ai.prompt_template_manager",
    "desktop_automation_agent.rate_limiter": ".resilience.rate_limiter",
    "desktop_automation_agent.resolution_adaptive_coordinate_manager": ".desktop.resolution_adaptive_coordinate_manager",
    "desktop_automation_agent.rest_api_action_executor": ".automation.rest_api_action_executor",
    "desktop_automation_agent.report_generator": ".automation.report_generator",
    "desktop_automation_agent.response_extractor_parser": ".ai.response_extractor_parser",
    "desktop_automation_agent.retry_engine": ".resilience.retry_engine",
    "desktop_automation_agent.screenshot_failure_recorder": ".observability.screenshot_failure_recorder",
    "desktop_automation_agent.screen_state_verifier": ".desktop.screen_state_verifier",
    "desktop_automation_agent.self_critique_improvement_loop": ".knowledge.self_critique_improvement_loop",
    "desktop_automation_agent.self_healing_recovery": ".resilience.self_healing_recovery",
    "desktop_automation_agent.sensitive_data_protector": ".resilience.sensitive_data_protector",
    "desktop_automation_agent.session_state_tracker": ".accounts.session_state_tracker",
    "desktop_automation_agent.shared_state_manager": ".agents.shared_state_manager",
    "desktop_automation_agent.specialist_agent_router": ".agents.specialist_agent_router",
    "desktop_automation_agent.structured_data_extractor": ".automation.structured_data_extractor",
    "desktop_automation_agent.target_application_prompt_injector": ".automation.target_application_prompt_injector",
    "desktop_automation_agent.task_queue_manager": ".agents.task_queue_manager",
    "desktop_automation_agent.template_image_matcher": ".desktop.template_image_matcher",
    "desktop_automation_agent.theme_adaptation": ".desktop.theme_adaptation",
    "desktop_automation_agent.smart_wait_engine": ".desktop.smart_wait_engine",
    "desktop_automation_agent.event_trigger_listener": ".desktop.event_trigger_listener",
    "desktop_automation_agent.animation_wait_module": ".desktop.animation_wait_module",
    "desktop_automation_agent.dashboard_data_provider": ".observability.dashboard_data_provider",
    "desktop_automation_agent.execution_trace_recorder": ".observability.execution_trace_recorder",
    "desktop_automation_agent.resource_usage_tracker": ".observability.resource_usage_tracker",
    "desktop_automation_agent.sla_monitor": ".observability.sla_monitor",
    "desktop_automation_agent.inter_step_pacing_controller": ".desktop.inter_step_pacing_controller",
    "desktop_automation_agent.ui_state_fingerprinter": ".desktop.ui_state_fingerprinter",
    "desktop_automation_agent.workflow_scheduler": ".automation.workflow_scheduler",
    "desktop_automation_agent.watchdog_timer": ".observability.watchdog_timer",
    "desktop_automation_agent.window_manager": ".desktop.window_manager",
    "desktop_automation_agent.workflow_audit_logger": ".observability.workflow_audit_logger",
    "desktop_automation_agent.workflow_skill_store": ".knowledge.workflow_skill_store",
}

for _legacy_name, _module_path in _LEGACY_MODULE_ALIASES.items():
    sys.modules.setdefault(_legacy_name, import_module(_module_path, __name__))

__all__ = [
    "ActionLogEntry",
    "ActiveWorkflowStatus",
    "AntiLoopDetectionResult",
    "AntiLoopDetector",
    "AntiLoopEventRecord",
    "AntiLoopStepExecution",
    "AntiLoopTriggerType",
    "ActionAllowlistEnforcer",
    "AccessibilityElement",
    "AccessibilityElementState",
    "AccessibilityQueryResult",
    "AccessibilityTree",
    "AccessibilityTreeReader",
    "AdaptiveTimingBaselineRecord",
    "AdaptiveTimingCalibrationResult",
    "AdaptiveTimingCalibrator",
    "AdaptiveTimingSessionProfile",
    "AnimationCompletionSignal",
    "AnimationTransitionWaitModule",
    "AnimationWaitLogEntry",
    "AnimationWaitRequest",
    "AnimationWaitResult",
    "AIInterfaceConfiguration",
    "AIInterfaceElementMatch",
    "AIInterfaceElementSelector",
    "AIInterfaceNavigationResult",
    "AIInterfaceNavigator",
    "AIInterfaceObservation",
    "AIInterfaceStatus",
    "AIInterfaceSubmitMode",
    "ApplicationLaunchAttempt",
    "ApplicationLaunchMode",
    "ApplicationLaunchRequest",
    "ApplicationLaunchResult",
    "ApplicationLaunchStatus",
    "ApplicationLauncher",
    "ApplicationRegistry",
    "ApplicationRegistrySnapshot",
    "ApplicationStartupSignature",
    "AutomationPluginDeclaration",
    "AutomationPluginExecutionResult",
    "AutomationPluginLoader",
    "AutomationPluginLoaderResult",
    "AutomationPluginRecord",
    "BranchComparisonOperator",
    "BranchConditionSpecification",
    "BranchConditionType",
    "BranchEvaluationContext",
    "BranchEvaluationRecord",
    "BranchEvaluationResult",
    "BranchOption",
    "BranchValueSource",
    "CICDPipelineIntegrationModule",
    "CICDReportMode",
    "CICDRunResult",
    "CICDStepOutcome",
    "CICDTriggerPayload",
    "CICDWorkflowSpecification",
    "AnomalyCategory",
    "AnomalyDetectionResult",
    "AnomalyDetector",
    "AnomalyRecord",
    "PipelinePauseDecision",
    "PipelineReviewRequest",
    "PipelineReviewResult",
    "PipelineResponseAction",
    "PipelineStatus",
    "RetryAttemptLog",
    "RetryConfiguration",
    "RetryDisposition",
    "RetryExceptionRule",
    "RetryExhaustedError",
    "RetryFailureResult",
    "SandboxAccessAttempt",
    "SandboxAccessType",
    "SandboxIsolationMode",
    "SandboxIsolationPolicy",
    "SandboxIsolationResult",
    "SandboxViolationRecord",
    "SandboxWorkerLaunchSpec",
    "RESTAPICallLog",
    "RESTAPIActionExecutor",
    "RESTAPIExecutorResult",
    "RESTAPIMethod",
    "RESTAPIRequest",
    "RESTAPIResponse",
    "RateLimiter",
    "RateLimiterResult",
    "RateLimiterSnapshot",
    "RateLimitExecutionRecord",
    "RateLimitRequest",
    "RateLimitRule",
    "RateLimitScope",
    "RateLimitWindow",
    "RateUsageMetric",
    "RecoveryStrategy",
    "MissedExecutionPolicy",
    "TaskDecompositionLevel",
    "TaskDecompositionNode",
    "TaskDecompositionResult",
    "TaskDecompositionTree",
    "TaskPriority",
    "TaskQueueAlert",
    "TaskQueueDepthMetric",
    "TaskQueueOperationResult",
    "TaskQueueSnapshot",
    "ResponseExtractionAttempt",
    "ResponseExtractionConfiguration",
    "ResponseExtractionResult",
    "ResponseExtractorParser",
    "ExponentialBackoffRetryEngine",
    "FailSafeActivationRecord",
    "FailSafeActivationResult",
    "FailSafeController",
    "FailSafeResourceReleaseResult",
    "FailSafeTriggerType",
    "ResponseProcessingMode",
    "ResponseValidationMode",
    "ResponseValidationResult",
    "ResourceUsageAggregate",
    "ResourceUsageRunRecord",
    "ResourceUsageTrackerResult",
    "ResourceUsageTrendReport",
    "ResourceUsageTrendSnapshot",
    "ResourceUsageSnapshot",
    "SLAAlertRecord",
    "SLAComplianceSnapshot",
    "SLADailyPerformanceReport",
    "SLAMonitorResult",
    "SLARecordedStepDuration",
    "SLARunRecord",
    "SLASlowestStepContribution",
    "SLAWorkflowConfiguration",
    "ImprovementProposalRecord",
    "ImprovementProposalStatus",
    "ImprovementTargetType",
    "HierarchicalTaskDecomposer",
    "IPCChannelType",
    "IPCConnectionRecord",
    "IPCMessage",
    "IPCModule",
    "IPCOperationResult",
    "IPCSnapshot",
    "AccountExecutionMode",
    "AccountLoadMetric",
    "AccountRecord",
    "AccountRegistry",
    "AccountRegistryResult",
    "AccountRegistrySnapshot",
    "AccountRotationOrchestrator",
    "AccountRotationResult",
    "AccountUsageEvent",
    "ApprovalDecision",
    "ApprovalGateAction",
    "ApprovalGateModule",
    "ApprovalGateResult",
    "ApprovalRequest",
    "ApprovalResponse",
    "ApprovalRiskLevel",
    "ApprovalTimeoutPolicy",
    "AllowlistCheckRequest",
    "AllowlistCheckResult",
    "AllowlistRuleSet",
    "AllowlistScope",
    "ConfidenceBasedAutoRouting",
    "ConfidenceRoutingDecision",
    "ConfidenceRoutingDisposition",
    "ConfidenceRoutingResult",
    "ConfidenceRoutingSnapshot",
    "ConfidenceThresholdRule",
    "EscalationManager",
    "EscalationManagerResult",
    "EscalationRecord",
    "EscalationRequest",
    "EscalationResolution",
    "EscalationResponse",
    "EscalationSnapshot",
    "EscalationTriggerType",
    "ExecutionTraceEvent",
    "ExecutionTraceEventType",
    "ExecutionTraceRecord",
    "ExecutionTraceRecorder",
    "ExecutionTraceResult",
    "HumanReviewDecisionRecord",
    "HumanReviewDecisionType",
    "HumanReviewInterface",
    "HumanReviewInterfaceResult",
    "HumanReviewInterfaceSnapshot",
    "HumanReviewPendingItem",
    "KeyboardHotkeyBackend",
    "AutomationTask",
    "ActionFailurePoint",
    "ActionHistoryAnalysisReport",
    "ActionHistoryAnalysisResult",
    "ActionHistoryAnalyzer",
    "ActionHistorySequencePattern",
    "AgentBusDeliveryResult",
    "AgentBusMessage",
    "AgentBusSubscription",
    "AgentHandoffContext",
    "AgentHandoffProtocol",
    "AgentHandoffReason",
    "AgentHandoffRecord",
    "AgentHandoffResult",
    "AgentMessageBus",
    "create_agent",
    "DesktopAutomationAgent",
    "ParallelWorkerPool",
    "SandboxIsolationManager",
    "TaskQueueManager",
    "RotationExecutionEvent",
    "RotationExecutionSnapshot",
    "RotationTask",
    "BrowserProfileRecord",
    "BrowserProfileResult",
    "BrowserProfileSnapshot",
    "BrowserProfileSwitcher",
    "BrowserSessionRecord",
    "CheckpointDecision",
    "CheckpointManager",
    "CheckpointRestoreResult",
    "CheckpointResumePolicy",
    "ClipboardContent",
    "ClipboardContentType",
    "ClipboardBridgeFormat",
    "ClipboardBridgeResult",
    "ClipboardDataBridge",
    "ClipboardEvent",
    "ClipboardManager",
    "ClipboardOperationResult",
    "ClipboardPasteMode",
    "ClipboardVerificationResult",
    "ComplianceAccountSessionRecord",
    "ComplianceActionRecord",
    "ComplianceApprovalRecord",
    "ComplianceAuditReport",
    "ComplianceAuditReportGenerator",
    "ComplianceAuditReportResult",
    "ComplianceEscalationRecord",
    "ComplianceFailureRecord",
    "ComplianceSensitiveAccessRecord",
    "COMAutomationConnector",
    "COMAutomationResult",
    "COMAutomationSession",
    "ConditionDescription",
    "ConditionalBranchEvaluator",
    "ConditionValidationResult",
    "CoordinateAdaptationResult",
    "DashboardAccountStatus",
    "DashboardDataProviderResult",
    "DashboardSnapshot",
    "DashboardWorkerStatus",
    "DatabaseBufferedOperation",
    "DatabaseCheckpointRecord",
    "DatabaseErrorRecord",
    "DatabaseExtractedDataRecord",
    "DatabaseLoggingResult",
    "DatabaseLoggingSnapshot",
    "DatabaseLogOperationType",
    "DatabaseMetricRecord",
    "DatabaseStepRecord",
    "DatabaseWorkflowEventRecord",
    "DatabaseWorkflowRecord",
    "DynamicRegionOfInterest",
    "DynamicRegionResult",
    "DisplayConfigurationChangeResult",
    "DisplayConfigurationSnapshot",
    "CredentialAccessEvent",
    "CredentialKind",
    "CredentialRecord",
    "CredentialVaultResult",
    "CredentialVaultSnapshot",
    "SecureCredentialValue",
    "SensitiveAccessEvent",
    "SensitiveDataProtector",
    "SensitiveProtectionResult",
    "VaultAPIError",
    "DataExportDestination",
    "DataExportDestinationType",
    "DataExportFileFormat",
    "DataExportLogEntry",
    "DataExportPipeline",
    "DataExportResult",
    "DataExportValidationFailure",
    "FileBasedDataExchange",
    "FileDataExchangeResult",
    "HybridAutomationResult",
    "HybridAutomationSession",
    "DeadLetterItem",
    "DeadLetterOperationResult",
    "DeadLetterQueueHandler",
    "DeadLetterSnapshot",
    "DesktopPerceptionEngine",
    "AutomationEpisode",
    "EpisodicMemoryLogger",
    "EpisodicMemoryResult",
    "EpisodicMemorySearchMatch",
    "FeedbackEventRecord",
    "FeedbackEventType",
    "FeedbackLoopCollector",
    "FeedbackLoopResult",
    "FeedbackPatternSummary",
    "ErrorCategory",
    "ErrorClassificationRecord",
    "ErrorClassificationResult",
    "ErrorClassifier",
    "FailureArchiveQuery",
    "FailureArchiveRecord",
    "FailureArchiveResult",
    "DesktopWindowManager",
    "InterStepPacingController",
    "MultiMonitorDisplayHandler",
    "DesktopState",
    "InputAction",
    "InputActionType",
    "InputSimulationResult",
    "InputTarget",
    "PacingAssignment",
    "PacingContext",
    "PacingDecision",
    "PacingProfile",
    "PluginActionRoute",
    "DialogClassification",
    "DialogHandlingRequest",
    "DialogResponse",
    "EventDrivenTriggerListener",
    "EventTriggerDefinition",
    "EventTriggerListenerResult",
    "EventTriggerListenerStatus",
    "EventTriggerRecord",
    "FormAutomationModule",
    "FormAutomationResult",
    "FormFieldContext",
    "FormFieldResult",
    "FormFieldType",
    "FormFieldValue",
    "GraphBasedWorkflowPlanner",
    "IdempotencyGuard",
    "IdempotencyRecord",
    "IdempotencyResult",
    "IdempotencySnapshot",
    "InteractionStateSnapshot",
    "NavigationSequenceMode",
    "NavigationSequenceResult",
    "NavigationStep",
    "NavigationStepActionType",
    "NavigationStepOutcome",
    "NavigationStepSequencer",
    "NotificationChannel",
    "NotificationChannelType",
    "NotificationDispatchRecord",
    "NotificationDispatcher",
    "NotificationDispatcherResult",
    "NotificationDispatcherSnapshot",
    "NotificationEventType",
    "NotificationMessage",
    "LocatorCandidate",
    "LocatorResult",
    "LocatorStrategy",
    "LocatorTarget",
    "LineEndingStyle",
    "LoadBalancerDecisionRecord",
    "LoadBalancerResult",
    "LoadBalancerSnapshot",
    "KnownApplicationRecord",
    "MultiAccountLoadBalancer",
    "OCRExtractionResult",
    "OCRExtractor",
    "OCRTextBlock",
    "OCRTextMatchResult",
    "ActionOptimizationHint",
    "ActionRetryRateSummary",
    "ActionStepDurationSummary",
    "OrchestratorAgentCore",
    "OrchestratorAgentResult",
    "OrchestratorExecutionSummary",
    "OrchestratorSubtask",
    "OrchestratorSubtaskResult",
    "OrchestratorSubtaskStatus",
    "OrchestratorTaskPlan",
    "PerformanceMetricsCollector",
    "PerformanceMetricsResult",
    "PerformanceMetricsSnapshot",
    "RealTimeDashboardDataProvider",
    "ResourceUsageTracker",
    "SLAMonitor",
    "MetricsDegradationDirection",
    "MetricsDegradationRecord",
    "MonitorDescriptor",
    "OpenCVImageMatcherBackend",
    "PILDifferenceBackend",
    "PILVirtualDesktopCaptureBackend",
    "DPAPICipher",
    "PromptTemplateManager",
    "PromptTemplateRecord",
    "PromptTemplateResult",
    "PromptTemplateSnapshot",
    "PromptTemplateVersion",
    "PyAutoGUIBackend",
    "PyAutoGUIPointerBackend",
    "PyAutoGUIScreenCaptureBackend",
    "PyAutoGUIScreenshotBackend",
    "QueueDepthStatus",
    "ResolutionAdaptiveCoordinateManager",
    "ScreenBrightnessThemeHeuristic",
    "MultiStrategyElementLocator",
    "MenuDialogInteractionLog",
    "MenuDialogNavigationResult",
    "MenuDialogNavigator",
    "MenuNavigationRequest",
    "ExternalWorkflowTriggerReceiver",
    "LangGraphNodeDefinition",
    "LangGraphStateConnector",
    "MCPToolAdapter",
    "MCPToolCallRequest",
    "MCPToolDefinition",
    "MultiApplicationWorkflowCoordinator",
    "PerceptionArtifact",
    "PerceptionResult",
    "PerceptionSource",
    "PluginActionRouter",
    "PrePostConditionValidator",
    "PromptFieldContext",
    "PromptInjectionMethod",
    "PromptInjectionResult",
    "PromptInjectionTarget",
    "PromptPerformanceRecord",
    "PromptPerformanceReport",
    "PromptPerformanceResult",
    "PromptPerformanceTracker",
    "PromptPipelineResult",
    "PromptPipelineRunner",
    "PromptPipelineStep",
    "PromptPipelineStepLog",
    "PromptReadbackMethod",
    "PromptTemplatePerformanceSummary",
    "ResponseExtractorParser",
    "TargetApplicationPromptInjector",
    "TriggerAuthenticationConfiguration",
    "WebDesktopHybridAutomation",
    "WorkflowReportGenerator",
    "WorkflowScheduler",
    "WorkflowTemplateLibrary",
    "WorkflowVersionController",
    "WorkflowReportResult",
    "WorkflowReportSummary",
    "WorkflowReportTimelineItem",
    "WorkflowRunReport",
    "ReferenceTemplateMetadata",
    "ResolutionCalibrationProfile",
    "ResolutionReferenceElement",
    "ResolutionVerificationReference",
    "ResolutionVerificationResult",
    "ScreenChangeDetectionMonitor",
    "ScreenChangeEvent",
    "ScreenChangeResult",
    "ScreenCheckType",
    "ScreenshotOnFailureRecorder",
    "SelfCritiqueImprovementLoop",
    "SelfCritiqueResult",
    "SharedStateConflictPolicy",
    "SharedStateField",
    "SharedStateManager",
    "SharedStateResult",
    "SharedStateSnapshot",
    "SharedStateWriteLog",
    "StructuredDataExtractor",
    "PaginationAdvanceMode",
    "PaginationConfiguration",
    "ScreenStateVerifier",
    "ScreenVerificationCheck",
    "ScreenVerificationCheckResult",
    "ScreenVerificationResult",
    "SelfHealingRecoveryModule",
    "SelfHealingRecoveryRequest",
    "SelfHealingRecoveryResult",
    "SQLiteConnectionPool",
    "SpecialistAgentRecord",
    "SpecialistAgentRouter",
    "SpecialistRouterResult",
    "BusRecipientKind",
    "SessionHealthEvent",
    "SessionState",
    "SessionStateTracker",
    "SessionTrackerSnapshot",
    "SessionValidationResult",
    "SafeInputSimulator",
    "ScreenBounds",
    "SmartWaitEngine",
    "SmartWaitLogEntry",
    "SmartWaitRequest",
    "SmartWaitResult",
    "StaticScreenInspector",
    "StartupTimingBenchmark",
    "StepExecutionRateStatus",
    "SubprocessApplicationLauncherBackend",
    "SubprocessBrowserLauncher",
    "TemplateCaptureResult",
    "TemplateImageMatcher",
    "TemplateMatch",
    "TemplateSearchRequest",
    "TemplateSearchResult",
    "ThemeAdaptationModule",
    "ThemeDetectionResult",
    "ThemeTemplateReferenceSet",
    "TriggerType",
    "UILandmark",
    "UITheme",
    "UIStateFingerprint",
    "UnexpectedDialogPolicy",
    "ValidationDisposition",
    "ValidationPhase",
    "WaitType",
    "RoutingDecisionRecord",
    "WatchdogEvent",
    "WatchdogEventType",
    "WatchdogStatus",
    "WatchdogTimer",
    "WorkflowAuditLogEntry",
    "WorkflowAuditLogger",
    "WorkflowAuditOutcome",
    "WorkflowAuditQuery",
    "WorkflowAuditResult",
    "WorkflowContext",
    "WorkflowCheckpoint",
    "WorkflowGraphCondition",
    "WorkflowGraphConditionOperator",
    "WorkflowGraphDefinition",
    "WorkflowDefinitionVersion",
    "WorkflowGraphEdge",
    "WorkflowGraphEdgeType",
    "WorkflowGraphNode",
    "WorkflowGraphNodeType",
    "WorkflowGraphPlanResult",
    "WorkflowGraphState",
    "WorkflowCoordinatorResult",
    "WorkflowDataExchangeMode",
    "WorkflowExchangeRequest",
    "WorkflowSkillDocument",
    "WorkflowSkillSearchMatch",
    "WorkflowSkillStep",
    "WorkflowSkillStore",
    "WorkflowSkillStoreResult",
    "WorkflowSkillVersion",
    "WorkflowTemplateCompositionComponent",
    "WorkflowTemplateDocument",
    "WorkflowTemplateLibraryResult",
    "WorkflowTemplateLibrarySnapshot",
    "WorkflowTemplateParameter",
    "WorkflowTemplateSearchMatch",
    "WorkflowTemplateVersion",
    "StructuredDataExtractionConfiguration",
    "StructuredDataExtractionMode",
    "StructuredDataExtractionResult",
    "StructuredDataFieldSchema",
    "StructuredDataFieldType",
    "StructuredDataPageResult",
    "StructuredDataRecord",
    "StructuredDataSchema",
    "StepExecutionRateStatus",
    "StepLatencySummary",
    "StepRetryRateMetric",
    "VaultCredentialAccessEvent",
    "VaultCredentialCacheEntry",
    "VaultCredentialResult",
    "WorkflowSuccessMetric",
    "WorkflowEventTrigger",
    "WorkflowEventType",
    "WorkflowRunRecord",
    "WorkflowSchedule",
    "WorkflowSchedulerEvent",
    "WorkflowSchedulerResult",
    "WorkflowSchedulerSnapshot",
    "WorkflowVersionControlResult",
    "WorkflowVersionDiff",
    "WorkflowVersionSnapshot",
    "WorkflowVersionTag",
    "WorkflowTriggerType",
    "SandboxAccessAttempt",
    "SandboxAccessType",
    "SandboxIsolationMode",
    "SandboxIsolationPolicy",
    "SandboxIsolationResult",
    "SandboxViolationRecord",
    "SandboxWorkerLaunchSpec",
    "WorkerAssignment",
    "WorkerExecutionMode",
    "WorkerPoolOperationResult",
    "WorkerPoolSnapshot",
    "WorkerRecord",
    "WorkerSessionContext",
    "WorkerStatus",
    "ThrottlingEvent",
    "ThrottlingEventType",
    "WorkflowStep",
    "WorkflowStepResult",
    "TesseractOCRBackend",
    "UIStateFingerprinter",
    "Win32ClipboardBackend",
    "Win32MonitorBackend",
    "Win32ThemeBackend",
    "Win32PlatformTextInputBackend",
    "Win32WindowBackend",
    "Win32WindowManager",
    "WindowContext",
    "WindowOperationResult",
    "WindowReference",
    "WindowZone",
    "WindowZoneType",
    "WindowState",
]
